#!/usr/bin/env bash 
# Bash script that transfers a file from our client to a server

if ("$#" -ne 3); then
    ecoh "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
file_path = $1
Server_IP = $2
Server_usrname = $3
ssh_private_key_path = $4

scp -i "$sssh_private_key_path" -o StrictHostKeyChecking=no "$file_path" "$Server_usrname"@"$Server_IP":~
